### ISSUE TITLE
Fix responsiveness in Frontend

### ISSUE THREAD

**Issue by Rungrukuk** [Rungrukuk/Social-Media#40]
Need to make website responsive

**Comment by yasukomiyazawa** [comment]
Please add me.

**Comment by Rungrukuk** [comment]
> Please add me.
I have sent and invite to you. Please note that I'm working on huge branch. I'm planning to merge that branch in this weekend and I have contributed a lot in frontend. I'm not going to say my frontend skills are good :D but you can trust me in backend Yoroshiku Onegaishimasu
